version: '3.8'

services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=test
    ports:
      - '13306:3306'
    volumes:
      - ./.mysql:/docker-entrypoint-initdb.d
    command:
      [mysqld, --character-set-server=utf8, --collation-server=utf8_general_ci]